name: passify
description: "A secure password manager app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.3.5
  smooth_page_indicator: ^1.1.0
  file_picker: ^8.1.7
  path_provider: ^2.1.5
  crypto: ^3.0.6
  encrypt: ^5.0.3
  share_plus: ^10.1.4
  flutter_secure_storage: ^4.2.1
  vibration: ^3.0.0
  package_info_plus: ^8.1.3
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf